### ISSUE TITLE
enable editing

### ISSUE THREAD

**Issue by landam** [ctu-geoforall-lab-projects/dp-svoboda-2017#3]
Background: GDAL creates internal SQLite DB when reading VFK data. This DB could be open by PU plugin in write mode.

Problem:

1) GDAL 2.0-2.1 doesn't recognize geometry:

```
ogrinfo Export_vse.db PAR -so
INFO: Open of `Export_vse.db'
      using driver `SQLite' successful.

Layer name: PAR
Geometry: Unknown (any)  <----------- HERE
Feature Count: 608
Warning 1: Integer overflow occurred when trying to set 32bit field.
Warning 1: Integer overflow occurred when trying to set 32bit field.
Warning 1: Integer overflow occurred when trying to set 32bit field.
...
```

2) GDAL 2.2 recognizes geometry but datasource is open by VFK driver (in read-only mode)

```
ogrinfo exportvse.db PAR -fid 1
Warning 1: SBP: 2 features with invalid or empty geometry
Warning 1: DPM: 347 features with invalid or empty geometry
Had to open data source read-only.
INFO: Open of `exportvse.db'
      using driver `VFK' successful.

Layer name: PAR
Geometry: Polygon  <--- OK
Feature Count: 607
```

What we want:
- open DB by SQLite driver in writeable mode
- read geometry created by VFK driver

**Comment by landam** [comment]
Details: only subset of attributes should be shown:
- KMENOVE_CISLO_PAR
- PODDELENI_CISLA_PAR
- VYMERA_PARCELY

Attribute table will contain new (editable) and original (read-only) values.

**Comment by landam** [comment]
@svoboond GDAL's SQLite driver requires `geometry_columns` and `spatial_ref_sys` tables in order to read features' geometry, eg.

```
CREATE TABLE geometry_columns (     f_table_name VARCHAR,      f_geometry_column VARCHAR,      geometry_type INTEGER,      coord_dimension INTEGER,      srid INTEGER,     geometry_format VARCHAR );
INSERT INTO `geometry_columns` VALUES ('PAR','geometry',3,2,5514,'WKB');

CREATE TABLE spatial_ref_sys        (     srid INTEGER UNIQUE,     auth_name TEXT,     auth_srid TEXT,     srtext TEXT);
INSERT INTO `spatial_ref_sys` VALUES (5514,'EPSG','5514','PROJCS["S-JTSK / Krovak East North",GEOGCS["S-JTSK",DATUM["System_Jednotne_Trigonometricke_Site_Katastralni",SPHEROID["Bessel 1841",6377397.155,299.1528128,AUTHORITY["EPSG","7004"]],TOWGS84[570.8,85.7,462.8,4.998,1.587,5.261,3.56],AUTHORITY["EPSG","6156"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4156"]],PROJECTION["Krovak"],PARAMETER["latitude_of_center",49.5],PARAMETER["longitude_of_center",24.83333333333333],PARAMETER["azimuth",30.28813972222222],PARAMETER["pseudo_standard_parallel_1",78.5],PARAMETER["scale_factor",0.9999],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["X",EAST],AXIS["Y",NORTH],AUTHORITY["EPSG","5514"]]');
```

Suggested workflow:
1. check if DB exists
   1. open VFK file with VFK driver, load PAR layer and get number features (this should load features' geometry into DB)
   2. close datasource
2. open connection with DB (using Qt)
   1. check if `geometry_columns` and `spatial_ref_sys` tables exists, if not than load them from sql file (distributed by plugin)
   2. connection can be kept open for further queries
3. open DB by GDAL (force to use SQLite driver, GDAL 2.2+ is using VFK driver by default), datasource must be open in update mode
   1. add PAR layer into QGIS

**Comment by svoboond** [comment]
@landam How can I force GDAL to use SQLite driver when loading PAR layer into QGIS?

I can open the database with SQLite driver like this:

```
sqliteDriver = ogr.GetDriverByName('SQLite')
sqliteDataSource = sqliteDriver.Open(str(dbPath))
```

But when I want to load PAR layer into QGIS, this syntax does not allow me to open it with specific driver:

```
composedURI = str(dbPath) + "|layername=" + vfkLayerCode
layer = QgsVectorLayer(composedURI, layerName, 'ogr')
```

It works in GDAL 2.1 because it chooses SQLite driver, but it won't work in GDAL 2.2 since it uses VFK driver.

Constructor of QgsVectorLayer accepts only strings, not data source.

**Comment by landam** [comment]
See related discussion on ML: https://lists.osgeo.org/pipermail/qgis-developer/2016-October/045614.html

```
blacklisted_driver = gdal.GetDriverByName('driver_you_dont_want')
blacklisted_driver.Deregister()
layer = QgsVectorLayer(composedURI, layerName, 'ogr')
# do all the stuff you need with the layer
blacklisted_driver.Register()
```

Another option would to remove or disable (using environmental variable - `OGR_VFK_FORCE_READ_DB=ON/OFF`) GDAL VFK driver ability to read DB datasources in GDAL 2.2. GDAL VFK driver in version 2.2 could also create missing metatables `geometry_columns` and `spatial_ref_sys`.

**Comment by svoboond** [comment]
Comment: I could not find a way how to hide and organize columns in attribute table by using PyQGIS.
Therefore I asked at [GIS Stack Exhange](http://gis.stackexchange.com/questions/215946/hide-column-in-attribute-table-by-using-pyqgis) but no one has replied so far.

There are few options if we don't solve this:
1) we could leave it like it is now
2) we could copy the table with different column order (optionally delete the original one and rename it), so the columns would be displayed first in attribute table
3) we could create new table only with columns we want (optionally delete the original one and rename it)
