### ISSUE TITLE
select features (unselect)

### ISSUE THREAD

**Issue by landam** [ctu-geoforall-lab-projects/dp-svoboda-2017#6]
QGIS allows selecting features by point, rectangle and polygon. Currently it's not possible (or we didn't find) unselect by polygon. Testcase:

1) select features by polygon
2) draw polygon inside of unselected features (to unselect)

This workflow works for 'select by point', but for 'select by rectangle/polygon'.

**Comment by landam** [comment]
Details: after selecting features user gives category
- 1 - v obvodu - resene
- 2 - v obvodu - neresene
- 3 - mimo obvod

**Comment by landam** [comment]
Feature: newly added parcels will get category automatically.

**Comment by svoboond** [comment]
Comment: I tried to unselect features in all available modes (by rectangle, polygon, freehand, radius) and it works.

The process is as follows:
1) select features
2) hold ctrl and choose features you want to unselect

**Comment by landam** [comment]
Seems to work, closing as invalid.
