### ISSUE TITLE
examination - notes

### ISSUE THREAD

**Issue by landam** [ctu-geoforall-lab-projects/dp-svoboda-2017#7]
Notes about examination:
- perimeter should not intersect parcels
- area (SGI vs. SPI) - threshold given by user
- reference point by surveying (new layer) - distance computed parcels' centre (teziste)

**Comment by svoboond** [comment]
Currently the issue with 'distance' analysis is that it takes really long to write the data into the database (more than a minute on my laptop). My plan is to add an option to calculate the distance only for selected features.

**Comment by svoboond** [comment]
Perimeter and area checks work, distance analysis as well.
