### ISSUE TITLE
appreciation (bpej)

### ISSUE THREAD

**Issue by landam** [ctu-geoforall-lab-projects/dp-svoboda-2017#8]
BPEJ given as a new layer. This layer is overlaid by parcel layer. The final price is rounded to 10CZK.

**Comment by svoboond** [comment]
@landam I suppose the BPEJ layer is vector. Is that right?
Do you have any example data I could use for testing? It would be good to know how the fields are named etc.

**Comment by svoboond** [comment]
BPEJ check works now.
